#apollo
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = application,public-conf.jdbc,public-conf.redis,public-conf.mongodb,public-conf.rabbitmq,public-conf.spring-cloud
dev.meta=http://apollo.tkfc.com:8084
fat.meta=http://apollo.tkfc.com:8084
uat.meta=http://apollo.tkfc.com:8084
pro.meta=http://apollo.tkfc.com:8084